version: "3"

services:
    react-native:
        environment:
            - USER_HOST=${USER}
        build: ./
        container_name: react-native
        ports:
            - "80"
        volumes:
            - /dev/bus/usb:/dev/bus/usb
            - ./project:/project
        restart: unless-stopped
        tty: true
        privileged: true
volumes:
  data:
    driver: "local"
