version: "3"

services:
    react-native:
        environment:
            - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.25.8 #IP Local
        build: ./
        container_name: react-native
        ports:
            - "8081:8081"
            - "19000:19000"
            - "19001:19001"
        volumes:
            - /dev/bus/usb:/dev/bus/usb #Don't work macOS
            - ./project:/project
        restart: unless-stopped
        tty: true
        privileged: true
volumes:
  data:
    driver: "local"
